language: java
jdk:
  - oraclejdk8    
  - oraclejdk7
  - openjdk7
  - openjdk6
  
node_js: stable

after_script:
  - git init
  - git config user.name "ysoserial"
  - git add .
  - git commit -m "Update "
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/z99/ysoserial.git
